name: flutter_chess_game
description: "A new Flutter project."

publish_to: 'none' # Não é necessário publicar este pacote no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.1
  sqflite: ^2.0.0+3       
  path: ^1.8.0            
  path_provider: ^2.0.15   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
